'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  FileText, 
  Download, 
  Share, 
  CheckCircle, 
  AlertTriangle,
  TrendingUp,
  Users,
  DollarSign,
  Target,
  AlertCircle
} from "lucide-react";
import { MemoData } from '@/lib/ai-chat-service';

interface InvestmentMemoProps {
  memoData: MemoData;
  onClose?: () => void;
}

export default function InvestmentMemo({ memoData, onClose }: InvestmentMemoProps) {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    
    // Generate PDF content
    const pdfContent = generatePDFContent(memoData);
    
    // Create and download PDF
    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${memoData.company_name}_Investment_Memo.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    setIsDownloading(false);
  };

  const generatePDFContent = (data: MemoData): string => {
    return `
INVESTMENT MEMO
${data.company_name}
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
${data.recommendation}

COMPANY OVERVIEW
${data.company_name} is addressing a significant market opportunity through their innovative approach.

BUSINESS MODEL
${data.business_model}

MARKET OPPORTUNITY
${data.market_opportunity}

TEAM STRENGTH
${data.team_strength}

FINANCIAL METRICS
${data.financial_metrics}

RISK ASSESSMENT
${data.risks}

INVESTMENT RECOMMENDATION
${data.recommendation}
Recommended Investment: ${data.investment_amount}
Estimated Valuation: ${data.valuation}

---
Generated by VeritasAI Investment Analysis System
    `.trim();
  };

  const getRecommendationColor = (recommendation: string) => {
    if (recommendation.includes('STRONG BUY')) return 'bg-green-100 text-green-800 border-green-200';
    if (recommendation.includes('BUY')) return 'bg-blue-100 text-blue-800 border-blue-200';
    if (recommendation.includes('HOLD')) return 'bg-yellow-100 text-yellow-800 border-yellow-200';
    return 'bg-gray-100 text-gray-800 border-gray-200';
  };

  return (
    <Card className="w-full max-w-4xl mx-auto">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Investment Memo - {memoData.company_name}
            </CardTitle>
            <CardDescription>
              AI-generated investment analysis and recommendation
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            <Button
              onClick={handleDownload}
              disabled={isDownloading}
              variant="outline"
              size="sm"
            >
              <Download className="h-4 w-4 mr-2" />
              {isDownloading ? 'Downloading...' : 'Download'}
            </Button>
            <Button variant="outline" size="sm">
              <Share className="h-4 w-4 mr-2" />
              Share
            </Button>
            {onClose && (
              <Button variant="ghost" size="sm" onClick={onClose}>
                Close
              </Button>
            )}
          </div>
        </div>
      </CardHeader>
      
      <CardContent className="space-y-6">
        {/* Executive Summary */}
        <div className="p-4 rounded-lg border-2 border-dashed">
          <div className="flex items-center gap-2 mb-3">
            <CheckCircle className="h-5 w-5 text-green-600" />
            <h3 className="text-lg font-semibold">Executive Summary</h3>
          </div>
          <div className={`p-3 rounded-lg border ${getRecommendationColor(memoData.recommendation)}`}>
            <p className="font-medium">{memoData.recommendation}</p>
          </div>
        </div>

        {/* Key Metrics */}
        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <DollarSign className="h-4 w-4" />
                Investment Range
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{memoData.investment_amount}</div>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <TrendingUp className="h-4 w-4" />
                Estimated Valuation
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{memoData.valuation}</div>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <Target className="h-4 w-4" />
                Status
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Badge variant="secondary" className="text-sm">
                AI Generated
              </Badge>
            </CardContent>
          </Card>
        </div>

        <Separator />

        {/* Detailed Analysis */}
        <div className="grid gap-6 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <Target className="h-4 w-4" />
                Business Model
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{memoData.business_model}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <TrendingUp className="h-4 w-4" />
                Market Opportunity
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{memoData.market_opportunity}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <Users className="h-4 w-4" />
                Team Strength
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{memoData.team_strength}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <DollarSign className="h-4 w-4" />
                Financial Metrics
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{memoData.financial_metrics}</p>
            </CardContent>
          </Card>
        </div>

        {/* Risk Assessment */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <AlertTriangle className="h-4 w-4" />
              Risk Assessment
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">{memoData.risks}</p>
          </CardContent>
        </Card>

        {/* Footer */}
        <div className="text-center text-xs text-muted-foreground pt-4 border-t">
          <p>Generated by VeritasAI Investment Analysis System</p>
          <p>This memo is based on AI analysis of the interview conversation</p>
        </div>
      </CardContent>
    </Card>
  );
}
