name: Deploy to New Firebase Project

on:
  push:
    branches: [ firebase-new-project ]
  pull_request:
    branches: [ firebase-new-project ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
      env:
        # Use secrets for new project
        NEXT_PUBLIC_PROCESS_INGESTION_URL: ${{ secrets.NEXT_PUBLIC_PROCESS_INGESTION_URL_NEW }}
        NEXT_PUBLIC_ON_FILE_UPLOAD_URL: ${{ secrets.NEXT_PUBLIC_ON_FILE_UPLOAD_URL_NEW }}
        NEXT_PUBLIC_TRIGGER_DILIGENCE_URL: ${{ secrets.NEXT_PUBLIC_TRIGGER_DILIGENCE_URL_NEW }}
        NEXT_PUBLIC_PROCESS_DILIGENCE_URL: ${{ secrets.NEXT_PUBLIC_PROCESS_DILIGENCE_URL_NEW }}
        NEXT_PUBLIC_SCHEDULE_INTERVIEW_URL: ${{ secrets.NEXT_PUBLIC_SCHEDULE_INTERVIEW_URL_NEW }}
        NEXT_PUBLIC_RUN_DILIGENCE_URL: ${{ secrets.NEXT_PUBLIC_RUN_DILIGENCE_URL_NEW }}
        NEXT_PUBLIC_QUERY_DILIGENCE_URL: ${{ secrets.NEXT_PUBLIC_QUERY_DILIGENCE_URL_NEW }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID_NEW }}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_NEW }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_NEW }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_NEW }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_NEW }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID_NEW }}
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID_NEW }}
        NEXT_PUBLIC_GA_PROPERTY_ID: ${{ secrets.NEXT_PUBLIC_GA_PROPERTY_ID_NEW }}
        NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME_NEW }}
        NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL_NEW }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Create Python virtual environment
      run: |
        cd functions
        python3.12 -m venv venv
        
    - name: Install Python dependencies
      run: |
        cd functions
        source venv/bin/activate
        pip install -r requirements.txt
        
    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_NEW }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Deploy Cloud Functions with Secrets
      run: |
        # Deploy process_ingestion_task
        gcloud functions deploy process_ingestion_task \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=process_ingestion_task \
          --trigger-topic=document-ingestion-topic \
          --timeout=540s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        # Deploy run_diligence
        gcloud functions deploy run_diligence \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=run_diligence \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        # Deploy query_diligence
        gcloud functions deploy query_diligence \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=query_diligence \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=60s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        # Deploy other functions
        gcloud functions deploy on_file_upload \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=on_file_upload \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy trigger_diligence \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=trigger_diligence \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy process_diligence_task \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=process_diligence_task \
          --trigger-topic=diligence-topic \
          --timeout=540s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy schedule_ai_interview \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=schedule_ai_interview \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest,SENDGRID_API_KEY=SENDGRID_API_KEY:latest,SENDGRID_FROM_EMAIL=SENDGRID_FROM_EMAIL:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy ai_feedback \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=ai_feedback \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy validate_memo_data \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=validate_memo_data \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy validate_market_size \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=validate_market_size \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy validate_competitors \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=validate_competitors \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=60s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy check_memo \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=check_memo \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=60s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy start_ai_interview \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=start_ai_interview \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        gcloud functions deploy submit_interview_answer \
          --gen2 \
          --runtime=python312 \
          --region=asia-south1 \
          --source=functions \
          --entry-point=submit_interview_answer \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1GB \
          --set-secrets=PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID_NEW }},VERTEX_AI_LOCATION=asia-south1 \
          --quiet
          
        echo "✅ All Cloud Functions deployed to new project!"
        
    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID_NEW }} --token ${{ secrets.FIREBASE_TOKEN_NEW }}